### ISSUE TITLE
Missing mandatory lifetime in example (Fig 7,8)

### ISSUE THREAD

**Issue by eurekaeru** [boucadair/draft-ietf-dots-signal-channel#1]
lifetime is a mandatory attribute, however it is missing in Fig. 7,8.
also, yang model tree should be updated as it is mandatory?
           |     +--rw lifetime?               int32

**Comment by boucadair** [comment]
Please see inline.

Cheers,
Med

De : __kaname__ [mailto:notifications@github.com]
Envoyé : dimanche 15 juillet 2018 10:31
À : boucadair/draft-ietf-dots-signal-channel
Cc : Subscribed
Objet : [boucadair/draft-ietf-dots-signal-channel] Missing mandatory lifetime in example (Fig 7,8) (#1)


lifetime is a mandatory attribute, however it is missing in Fig. 7,8.

[Med] Oh, you are right here. Please double check this fig 8:



A1                                      # map(1)

   01                                   # unsigned(1)

   A1                                   # map(1)

      02                                # unsigned(2)

      81                                # array(1)

         A3                             # map(4)

            18 23                       # unsigned(35)

            82                          # array(2)

              74                       # text(20)

                  323030313A6462383A363430313A3A312F313238 # "2001:db8:6401::1/128"

               74                       # text(20)

                  323030313A6462383A363430313A3A322F313238 # "2001:db8:6401::2/128"

            05                          # unsigned(5)

            83                          # array(3)

               A1                       # map(1)

                  06                    # unsigned(6)

                  18 50                 # unsigned(80)

               A1                       # map(1)

                  06                    # unsigned(6)

                  19 01BB               # unsigned(443)

               A1                       # map(1)

                  06                    # unsigned(6)

                  19 1F90               # unsigned(8080)

            08                          # unsigned(8)

            81                          # array(1)

               06                       # unsigned(6)

            19 0E10                     # unsigned(3600)

also, yang model tree should be updated as it is mandatory?
| +--rw lifetime? int32

[Med] mitigation-scope is used for both PUT, but also GET requests. This is why lifetime was not indicated as mandatory.

**Comment by eurekaeru** [comment]
```
A1                                      # map(1)
   01                                   # unsigned(1)
   A1                                   # map(1)
      02                                # unsigned(2)
      81                                # array(1)
         A3                             # map(3)
            06                          # unsigned(6)
            82                          # array(2)
               74                       # text(20)
                  323030313A6462383A363430313A3A312F313238 # "2001:db8:6401::1/128"
               74                       # text(20)
                  323030313A6462383A363430313A3A322F313238 # "2001:db8:6401::2/128"
            07                          # unsigned(7)
            83                          # array(3)
               A1                       # map(1)
                  08                    # unsigned(8)
                  18 50                 # unsigned(80)
               A1                       # map(1)
                  08                    # unsigned(8)
                  19 01BB               # unsigned(443)
               A1                       # map(1)
                  08                    # unsigned(8)
                  19 1F90               # unsigned(8080)
            0A                          # unsigned(10)
            81                          # array(1)
               06                       # unsigned(6)
            0E                          # unsigned(14)
            A1                          # map(1)
               19 0E10                  # unsigned(3600)
```
here is. CBOR key numbers are changed.

[Med] mitigation-scope is used for both PUT, but also GET requests. This is why lifetime was not indicated as mandatory.
-> OK, i thought lifetime is included in all of cases, but there would be other cases.

**Comment by boucadair** [comment]
Deal.

De : __kaname__ [mailto:notifications@github.com]
Envoyé : lundi 16 juillet 2018 22:27
À : boucadair/draft-ietf-dots-signal-channel
Cc : BOUCADAIR Mohamed IMT/OLN; Comment
Objet : Re: [boucadair/draft-ietf-dots-signal-channel] Missing mandatory lifetime in example (Fig 7,8) (#1)


A1                                      # map(1)

   01                                   # unsigned(1)

   A1                                   # map(1)

      02                                # unsigned(2)

      81                                # array(1)

         A3                             # map(3)

            06                          # unsigned(6)

            82                          # array(2)

               74                       # text(20)

                  323030313A6462383A363430313A3A312F313238 # "2001:db8:6401::1/128"

               74                       # text(20)

                  323030313A6462383A363430313A3A322F313238 # "2001:db8:6401::2/128"

            07                          # unsigned(7)

            83                          # array(3)

               A1                       # map(1)

                  08                    # unsigned(8)

                  18 50                 # unsigned(80)

               A1                       # map(1)

                  08                    # unsigned(8)

                  19 01BB               # unsigned(443)

               A1                       # map(1)

                  08                    # unsigned(8)

                  19 1F90               # unsigned(8080)

            0A                          # unsigned(10)

            81                          # array(1)

               06                       # unsigned(6)

            0E                          # unsigned(14)

            A1                          # map(1)

               19 0E10                  # unsigned(3600)

here is. CBOR key numbers are changed.

[Med] mitigation-scope is used for both PUT, but also GET requests. This is why lifetime was not indicated as mandatory.
-> OK, i thought lifetime is included in all of cases, but there would be other cases.

**Comment by boucadair** [comment]
Implemented in -21

**Comment by eurekaeru** [comment]
I made a mistake. The last 3 lines should be:
```
            0E                          # unsigned(14): lifetime
            19 0E10                     # unsigned(3600)
```

it means:
```
            0E                          # unsigned(14)
            A1                          # map(1)  <----- remove this
               19 0E10                  # unsigned(3600)
```

**Comment by boucadair** [comment]
Thanks for double checking. This is fixed in my local copy and take care of it as any comments we will receive later in the process.

De : __kaname__ [mailto:notifications@github.com]
Envoyé : mercredi 18 juillet 2018 14:15
À : boucadair/draft-ietf-dots-signal-channel
Cc : BOUCADAIR Mohamed IMT/OLN; State change
Objet : Re: [boucadair/draft-ietf-dots-signal-channel] Missing mandatory lifetime in example (Fig 7,8) (#1)


I made a mistake. The last 3 lines should be:

            0E                          # unsigned(14): lifetime

            19 0E10                     # unsigned(3600)

it means:

            0E                          # unsigned(14)

            A1                          # map(1)  <----- remove this

               19 0E10                  # unsigned(3600)
